/**
 * DataOriginLegend — displays a clear legend/badge row explaining
 * which data on the current page is LIVE, SIMULATED, MEASURED, or DEFINED.
 *
 * Usage:
 *   <DataOriginLegend items={['live', 'defined']} />
 *   <DataOriginTag type="live" />
 */

import React from 'react';

type DataOriginType = 'live' | 'simulated' | 'measured' | 'defined';

interface OriginConfig {
  label: string;
  description: string;
  bgColor: string;
  borderColor: string;
  textColor: string;
  dot: string;
  symbol: string;
}

const ORIGIN: Record<DataOriginType, OriginConfig> = {
  live: {
    label: 'LIVE',
    description: 'Retrieved from Kubernetes API in real time',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    textColor: 'text-emerald-400',
    dot: 'bg-emerald-400',
    symbol: '●',
  },
  simulated: {
    label: 'SIMULATED',
    description: 'Generated by Q-Validate device simulator',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    textColor: 'text-blue-400',
    dot: 'bg-blue-400',
    symbol: '◈',
  },
  measured: {
    label: 'MEASURED',
    description: 'Result of actual benchmark execution',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    textColor: 'text-purple-400',
    dot: 'bg-purple-400',
    symbol: '◆',
  },
  defined: {
    label: 'DEFINED',
    description: 'Kubernetes manifest / static configuration',
    bgColor: 'bg-gray-500/10',
    borderColor: 'border-gray-600/40',
    textColor: 'text-gray-400',
    dot: 'bg-gray-500',
    symbol: '▪',
  },
};

/** Inline badge — attach next to a section heading */
export function DataOriginTag({ type }: { type: DataOriginType }) {
  const cfg = ORIGIN[type];
  const isPulsing = type === 'live';
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded border text-[10px] font-mono font-bold
        ${cfg.bgColor} ${cfg.borderColor} ${cfg.textColor}`}
      title={cfg.description}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${cfg.dot} ${isPulsing ? 'animate-ping-slow' : ''}`} />
      {cfg.label}
    </span>
  );
}

/** Full legend row — place at the top or bottom of a page */
export function DataOriginLegend({ items }: { items: DataOriginType[] }) {
  return (
    <div className="flex flex-wrap items-center gap-2 font-mono">
      <span className="text-[10px] text-gray-600 uppercase tracking-widest">DATA SOURCE:</span>
      {items.map(type => {
        const cfg = ORIGIN[type];
        return (
          <span
            key={type}
            title={cfg.description}
            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg border text-[10px] font-bold
              ${cfg.bgColor} ${cfg.borderColor} ${cfg.textColor}`}
          >
            <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${cfg.dot}`} />
            <span>{cfg.label}</span>
            <span className="text-[9px] opacity-60 hidden sm:inline">— {cfg.description}</span>
          </span>
        );
      })}
    </div>
  );
}
