# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_service_pb2 as device__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub:
    """Service definition for controlling and querying simulated embedded devices
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/qvalidate.DeviceService/GetStatus',
                request_serializer=device__service__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.PowerOn = channel.unary_unary(
                '/qvalidate.DeviceService/PowerOn',
                request_serializer=device__service__pb2.PowerOnRequest.SerializeToString,
                response_deserializer=device__service__pb2.PowerOnResponse.FromString,
                _registered_method=True)
        self.PowerOff = channel.unary_unary(
                '/qvalidate.DeviceService/PowerOff',
                request_serializer=device__service__pb2.PowerOffRequest.SerializeToString,
                response_deserializer=device__service__pb2.PowerOffResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/qvalidate.DeviceService/Reset',
                request_serializer=device__service__pb2.ResetRequest.SerializeToString,
                response_deserializer=device__service__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.DeployBuild = channel.unary_unary(
                '/qvalidate.DeviceService/DeployBuild',
                request_serializer=device__service__pb2.DeployBuildRequest.SerializeToString,
                response_deserializer=device__service__pb2.DeployBuildResponse.FromString,
                _registered_method=True)
        self.InjectFault = channel.unary_unary(
                '/qvalidate.DeviceService/InjectFault',
                request_serializer=device__service__pb2.InjectFaultRequest.SerializeToString,
                response_deserializer=device__service__pb2.InjectFaultResponse.FromString,
                _registered_method=True)
        self.ClearFault = channel.unary_unary(
                '/qvalidate.DeviceService/ClearFault',
                request_serializer=device__service__pb2.ClearFaultRequest.SerializeToString,
                response_deserializer=device__service__pb2.ClearFaultResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/qvalidate.DeviceService/ExecuteCommand',
                request_serializer=device__service__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=device__service__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.CollectMetrics = channel.unary_unary(
                '/qvalidate.DeviceService/CollectMetrics',
                request_serializer=device__service__pb2.CollectMetricsRequest.SerializeToString,
                response_deserializer=device__service__pb2.CollectMetricsResponse.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """Service definition for controlling and querying simulated embedded devices
    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployBuild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectFault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearFault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=device__service__pb2.GetStatusRequest.FromString,
                    response_serializer=device__service__pb2.GetStatusResponse.SerializeToString,
            ),
            'PowerOn': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOn,
                    request_deserializer=device__service__pb2.PowerOnRequest.FromString,
                    response_serializer=device__service__pb2.PowerOnResponse.SerializeToString,
            ),
            'PowerOff': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOff,
                    request_deserializer=device__service__pb2.PowerOffRequest.FromString,
                    response_serializer=device__service__pb2.PowerOffResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=device__service__pb2.ResetRequest.FromString,
                    response_serializer=device__service__pb2.ResetResponse.SerializeToString,
            ),
            'DeployBuild': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployBuild,
                    request_deserializer=device__service__pb2.DeployBuildRequest.FromString,
                    response_serializer=device__service__pb2.DeployBuildResponse.SerializeToString,
            ),
            'InjectFault': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectFault,
                    request_deserializer=device__service__pb2.InjectFaultRequest.FromString,
                    response_serializer=device__service__pb2.InjectFaultResponse.SerializeToString,
            ),
            'ClearFault': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearFault,
                    request_deserializer=device__service__pb2.ClearFaultRequest.FromString,
                    response_serializer=device__service__pb2.ClearFaultResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=device__service__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=device__service__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'CollectMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectMetrics,
                    request_deserializer=device__service__pb2.CollectMetricsRequest.FromString,
                    response_serializer=device__service__pb2.CollectMetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qvalidate.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qvalidate.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """Service definition for controlling and querying simulated embedded devices
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/GetStatus',
            device__service__pb2.GetStatusRequest.SerializeToString,
            device__service__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PowerOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/PowerOn',
            device__service__pb2.PowerOnRequest.SerializeToString,
            device__service__pb2.PowerOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PowerOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/PowerOff',
            device__service__pb2.PowerOffRequest.SerializeToString,
            device__service__pb2.PowerOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/Reset',
            device__service__pb2.ResetRequest.SerializeToString,
            device__service__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployBuild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/DeployBuild',
            device__service__pb2.DeployBuildRequest.SerializeToString,
            device__service__pb2.DeployBuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InjectFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/InjectFault',
            device__service__pb2.InjectFaultRequest.SerializeToString,
            device__service__pb2.InjectFaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearFault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/ClearFault',
            device__service__pb2.ClearFaultRequest.SerializeToString,
            device__service__pb2.ClearFaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/ExecuteCommand',
            device__service__pb2.ExecuteCommandRequest.SerializeToString,
            device__service__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qvalidate.DeviceService/CollectMetrics',
            device__service__pb2.CollectMetricsRequest.SerializeToString,
            device__service__pb2.CollectMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
